### ISSUE TITLE
Use Stock Kernel

### ISSUE THREAD

**Issue by SpectreDev-007** [SailfishOS-SonyXperia/droid-hal-sony-edo#1]
Hi wouldn't it be better to use stock kernel than SODP kernel, you could use https://github.com/XperiaBrickers/android_kernel_sony_sm8250/tree/custom

**Comment by Thaodan** [comment]
Hey, please open a bug at https://github.com/SailfishOS-SonyXperia/bugs unless you have specific issue with this package.
